[features]
seeds = false
skip-lint = false
[programs.localnet]
pockets_program = "9ejfcqQpWYQqXMiPeZVHhhbNu3qufuLWzGzVEBQYBEgS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://rpc.helius.xyz/?api-key=5af76bac-2af7-45d6-87db-5cbcde1004b0 " #"Localnet"
wallet = "/Users/spacemandev/.config/solana/pockmZEzU9m8bkgHMtA3bmHASDFKv8N3kwkEbvQdd9K.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
